# Build react client
FROM node:22-alpine

# Working directory be app
WORKDIR /usr/src/app

# 1. Declare the build argument for the API URL
# This allows Jenkins to pass the EC2 IP into the build process
ARG REACT_APP_API_URL

# 2. Set it as an environment variable
# React scripts (npm run build) will look for variables starting with REACT_APP_
ENV REACT_APP_API_URL=$REACT_APP_API_URL

COPY package*.json ./

RUN npm install --silent

# Copy local files to app folder
COPY . .

# 3. Build the production application
# This bakes the actual EC2 IP into the static JavaScript files
RUN npm run build

EXPOSE 3000

# Use a production-ready command or serve the build folder
CMD ["npm", "start"]